# Generated by Django 5.2.4 on 2025-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='cancellation_requested',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_trial',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_activated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_converted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
